name:                 z-lab6-z-lab6-lib
version:              0.1.0.0
package-name:         lab6
lib-name:             lab6-lib
id:                   lab6-0.1.0.0-inplace-lab6-lib
key:                  lab6-0.1.0.0-inplace-lab6-lib
abi:                  inplace
exposed-modules:      Lab6
import-dirs:
    /Users/benjamin/Documents/GitHub/Toronto-Metropolitan-University/Winter-2026/CPS506/lab6/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lab6-0.1.0.0/l/lab6-lib/build/lab6-lib

library-dirs:
    /Users/benjamin/Documents/GitHub/Toronto-Metropolitan-University/Winter-2026/CPS506/lab6/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lab6-0.1.0.0/l/lab6-lib/build/lab6-lib

library-dirs-static:
    /Users/benjamin/Documents/GitHub/Toronto-Metropolitan-University/Winter-2026/CPS506/lab6/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lab6-0.1.0.0/l/lab6-lib/build/lab6-lib

dynamic-library-dirs:
    /Users/benjamin/Documents/GitHub/Toronto-Metropolitan-University/Winter-2026/CPS506/lab6/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lab6-0.1.0.0/l/lab6-lib/build/lab6-lib

data-dir:
    /Users/benjamin/Documents/GitHub/Toronto-Metropolitan-University/Winter-2026/CPS506/lab6/.

hs-libraries:         HSlab6-0.1.0.0-inplace-lab6-lib
depends:              base-4.18.3.0
haddock-interfaces:
    /Users/benjamin/Documents/GitHub/Toronto-Metropolitan-University/Winter-2026/CPS506/lab6/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lab6-0.1.0.0/l/lab6-lib/doc/html/lab6/lab6-lib.haddock

haddock-html:
    /Users/benjamin/Documents/GitHub/Toronto-Metropolitan-University/Winter-2026/CPS506/lab6/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lab6-0.1.0.0/l/lab6-lib/doc/html/lab6
