/**
 * Demonstration of the appointment classes.
 * DO NOT EDIT THIS FILE.
 */
public class AppointmentTester
{

    public static void main(String[] args)
    {

        DailyAppointment d = new DailyAppointment(2000, 8, 13, "Brush your teeth");
        System.out.println("------ TEST 1: Test that DailyAppointment Works Correctly ------");
        System.out.println("Date is 2009-09-13:");
        runOccursOnTest(d, 2009, 9, 13, true);
        runOccursOnTest(d, 2000, 6, 13, false);
        runOccursOnTest(d, 2001, 8, 13, true);
        runOccursOnTest(d, 2000, 8, 14, true);

        DailyAppointment d2 = new DailyAppointment(2024, 1, 1, "Take shower");
        System.out.println("------ TEST 2: Test that DailyAppointment Works Correctly on Second Date ------");
        System.out.println("Date is 2024-01-01:");
        runOccursOnTest(d2, 2024, 1, 1, true);
        runOccursOnTest(d2, 2023, 1, 1, false);
        runOccursOnTest(d2, 2024, 2, 29, true);
        runOccursOnTest(d2, 2025, 3, 14, true);


        System.out.println("------ TEST 3: Test that MonthlyAppointment Works Correctly ------");
        MonthlyAppointment m = new MonthlyAppointment(2003, 5, 20, "Visit grandma");
        System.out.println("For date 2003-04-20:");
        runOccursOnTest(m, 2003, 4, 20, false);
        runOccursOnTest(m, 2003, 7, 20, true);
        runOccursOnTest(m, 2003, 5, 20, true);
        runOccursOnTest(m, 2002, 5, 20, false);
        runOccursOnTest(m, 2003, 6, 19, false);

        System.out.println("------ TEST 4: Test that MonthlyAppointment Works Correctly on Second Date ------");
        MonthlyAppointment m2 = new MonthlyAppointment(2023, 3, 12, "Pay Bills");
        System.out.println("For date 2023-03-12:");
        runOccursOnTest(m2, 2023, 3, 13, false);
        runOccursOnTest(m2, 2023, 3, 12, true);
        runOccursOnTest(m2, 2023, 4, 12, true);
        runOccursOnTest(m2, 2022, 3, 12, false);
        runOccursOnTest(m2, 2023, 6, 19, false);
        runOccursOnTest(m2, 2024, 4, 12, true);
    }

    public static void runOccursOnTest(Appointment a, int year, int month, int day, boolean expected)
    {
        System.out.println("Checking date " + year + "-" + month + "-" + day);
        boolean output = a.occursOn(year, month, day);
        printTestResult(testBooleanOutput("occursOn", output, expected));
    }

    public static void printTestResult(boolean pass)
    {
        if (pass) {
            System.out.println("*** TEST PASSES ***\n");
        } else {
            System.out.println("*******************************************");
            System.out.println("*************** TEST FAILED ***************");
            System.out.println("*******************************************\n");
        }
    }

    public static boolean testBooleanOutput(String methodName, boolean output, boolean expected)
    {
        System.out.println("OUTPUT of " + methodName + ":   " + output);
        if (output != expected) {
            System.out.println("EXPECTED of " + methodName + ": " + expected);
            System.out.println("    INCORRECT OUTPUT");
            return false;
        }
        return true;
    }
}


